[project]
name = "focusflow"
version = "0.1.0"
description = "Rotate tasks. Stay on track. Try not to spiral."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flet[all]==0.28.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.9",
]
